-- MySQL Script generated by MySQL Workbench
-- 02/05/16 10:55:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema login_perfiles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login_perfiles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login_perfiles` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `login_perfiles` ;

-- -----------------------------------------------------
-- Table `login_perfiles`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_perfiles`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_perfiles`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_perfiles`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`, `profile_id`),
  INDEX `fk_user_profile_idx` (`profile_id` ASC),
  CONSTRAINT `fk_user_profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `login_perfiles`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_perfiles`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_perfiles`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menu_name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_perfiles`.`profile_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_perfiles`.`profile_action` (
  `profile_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `action_id`),
  INDEX `fk_profile_has_action_action1_idx` (`action_id` ASC),
  INDEX `fk_profile_has_action_profile1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_profile_has_action_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `login_perfiles`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_action_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `login_perfiles`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
